### ISSUE TITLE
Server Won't Work

### ISSUE THREAD

**Issue by wes1993** [karpach/remote-shutdown-pc#21] opened 2022-07-13 15:03 UTC
Hello,
With version remote-shutdown-pc-v1.0.40 the server won't work anymore.
Could you check?
Bye
Stefano

**Comment by oopiicaa** [comment] 2022-07-21 12:30
For me too - the latest version does not work (Windows 11). Didn't have the time to check further, just that the REST call from my Home Assistant times out. The app itself is let through the firewall on server machine. Reverting to previous version works fine.

**Comment by lorenzo-deluca** [comment] 2022-07-23 08:52
I've the same issue on Win11

**Comment by karpach** [comment] 2022-07-26 06:36
The issue is fixed in 1.52

**Closed by karpach** 2022-07-26 06:36 UTC

**Comment by oopiicaa** [comment] 2022-07-31 09:27
Version 1.53 again breaks it for me. 1.52 works okay.

**Comment by karpach** [comment] 2022-08-01 19:24
Yes, I started upgrade to VS 2022 and some version compatibility broke it again.

I fixed all issues in 1.1.2.
